apiVersion: v2
name: longhorn-system
description: Longhorn distributed block storage wrapper chart for Talos Linux
type: application
version: 0.1.0
appVersion: "1.7.2"

dependencies:
  - name: longhorn
    version: 1.7.2
    repository: https://charts.longhorn.io
