apiVersion: v2
name: cilium
description: Cilium CNI wrapper chart for Talos Linux
type: application
version: 0.1.0
appVersion: "1.18.5"

dependencies:
  - name: cilium
    version: 1.18.5
    repository: https://helm.cilium.io/
