apiVersion: v2
name: argocd
description: ArgoCD GitOps wrapper chart for Talos Linux
type: application
version: 0.1.0
appVersion: "2.13.2"

dependencies:
  - name: argo-cd
    version: 7.7.11
    repository: https://argoproj.github.io/argo-helm
